name: Unit Tests
on:
  push:
    branches: [ "main" ]
jobs:
  Unit-tests-on-windows:
    name: Unit Tests on Windows
    runs-on: windows-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: "Download latest tool4d release and expand"
        run: |
          curl https://resources-download.4d.com/release/20.x/20.0/latest/win/tool4d_v20.0_win.tar.xz -o tool4d.tar.xz -sLv
          tar xvzf tool4d.tar.xz -C tool4d
        shell: bash
      - name: "Run Unit Tests"
        run: |
          ./tool4d/tool4d.exe --project ${{ github.workspace }}\Project\tool4d-action-test.4DProject --dataless --skip-onstartup --startup-method "main"

  Unit-tests-on-macos:
    name: Unit Tests on macOS
    runs-on: macOS-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: "Download latest tool4d release and expand"
        run: |
          curl https://resources-download.4d.com/release/20.x/20.0/latest/mac/tool4d_v20.0_mac_x86.tar.xz -o tool4d.tar.xz -sL
          tar xvzf tool4d.tar.xz
      - name: "Run Project Unit Tests"
        run: |
          ./tool4d.app/Contents/MacOS/tool4d --project ${{ github.workspace }}/Project/tool4d-action-test.4DProject --dataless --skip-onstartup --startup-method "main"
          
