name: Release
on: 
  release:
    types: [published]
jobs:
  publish:
    name: Publish
    runs-on: windows-latest
    env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v3
      - name: Build with project file path
        uses: 4d/build4d-action@main
            
