name: 🚀 release
on: 
  release:
    types: [published]
jobs:
  publish:
    name: Publish
    runs-on: windo-latest

    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v3
      - name: Build with project file path
        uses: 4d/build4d-action@main
        with:
          actions: |
            - build
            - release
            
