name: run
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    name: "Run on ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: e-marchand/tool4d-action@main
      id: tool4drun
      with:
        project: "*"
        startup-method: main
    - uses: e-marchand/tool4d-action@main
      id: tool4drunwithparameters
      with:
        project: "*"
        startup-method: main
        user-param: "{ \"name\": \"goodbye\", \"word\": \"world\"}"
